### ISSUE TITLE
KillAbuse doesn't seem to work and prevent killing the same person within the duration set.

### ISSUE THREAD

**Issue by mibby** [confuser/Bukkit-KillStreaks#2]
KillStreaks v1.3.0
Paper dev 1449 (Spigot 1.12.2)

```
killAbuse:
  enabled: true
  maxKills: 1
  duration: 1800
```

You are able to kill the same person over and over again to get the reward. It still announces the kill and the streak rises.
