### ISSUE TITLE
Unable to remove '3' level from config.

### ISSUE THREAD

**Issue by mibby** [confuser/Bukkit-KillStreaks#4]
You are unable to remove the third levels reward from the config. Both when the server is down and when editing the config while the server is live with ```/ksreload```. It always comes back.

```
levels:
  '3':
    enabled: false
    announcement: '[displayName] &cis non-stop killing!'
  '1':
    enabled: true
    announcement: 'example'
    commands:
    - example
```
